# sprint_1 practice

In [ ]:
#task 1

In [16]:
import numpy as np

In [17]:
HR_Department=np.arange(1,501,1,int)
print(HR_Department, end = ' ')

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [18]:
Finance_Deprtment=np.arange(501,1001,1,int)
print(Finance_Deprtment,end= ' ')

[ 501  502  503  504  505  506  507  508  509  510  511  512  513  514
  515  516  517  518  519  520  521  522  523  524  525  526  527  528
  529  530  531  532  533  534  535  536  537  538  539  540  541  542
  543  544  545  546  547  548  549  550  551  552  553  554  555  556
  557  558  559  560  561  562  563  564  565  566  567  568  569  570
  571  572  573  574  575  576  577  578  579  580  581  582  583  584
  585  586  587  588  589  590  591  592  593  594  595  596  597  598
  599  600  601  602  603  604  605  606  607  608  609  610  611  612
  613  614  615  616  617  618  619  620  621  622  623  624  625  626
  627  628  629  630  631  632  633  634  635  636  637  638  639  640
  641  642  643  644  645  646  647  648  649  650  651  652  653  654
  655  656  657  658  659  660  661  662  663  664  665  666  667  668
  669  670  671  672  673  674  675  676  677  678  679  680  681  682
  683  684  685  686  687  688  689  690  691  692  693  694  695  696
  697 

In [19]:
IT_Department=np.arange(1002,1501,1,int)
print(IT_Department,end= ' ')

[1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015
 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029
 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043
 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057
 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071
 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085
 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099
 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112 1113
 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126 1127
 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140 1141
 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154 1155
 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168 1169
 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182 1183
 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196 1197
 1198 

In [20]:
Sales_Department=np.arange(1502,2001,1,int)
print(Sales_Department,end= ' ')

[1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515
 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1529
 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542 1543
 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556 1557
 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570 1571
 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584 1585
 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598 1599
 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1613
 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626 1627
 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640 1641
 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654 1655
 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668 1669
 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682 1683
 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696 1697
 1698 

In [21]:
#task 2

In [22]:
# HR_Employees

In [23]:
import numpy as np

In [27]:
HR_Department=np.random.randint(25000,50000,500)
HR_Department

array([43275, 46350, 41402, 43144, 35632, 26727, 46714, 32355, 38838,
       27313, 26356, 32862, 35945, 48829, 29447, 43062, 27835, 41623,
       45235, 31762, 26158, 28837, 43165, 48169, 32889, 46875, 42876,
       43967, 37139, 43744, 35718, 30923, 39501, 35919, 34366, 34795,
       28319, 46060, 45362, 45570, 28606, 27270, 29341, 48252, 26439,
       41212, 33174, 41972, 49289, 28154, 43766, 27940, 47126, 29647,
       29558, 29671, 44694, 40791, 41296, 38794, 30208, 41801, 37727,
       36983, 30882, 42536, 29970, 48033, 29608, 30334, 49066, 49820,
       47892, 25012, 36233, 35822, 25305, 47767, 32530, 29719, 48790,
       35837, 40838, 30100, 35202, 36448, 34733, 46080, 34380, 25209,
       35532, 29749, 31631, 43289, 44018, 44596, 37066, 42196, 41425,
       31525, 39269, 47646, 39436, 41321, 49261, 44231, 44824, 27848,
       32536, 28322, 45772, 35277, 27889, 35976, 35384, 45004, 35941,
       29105, 44456, 42906, 25784, 39819, 26695, 41233, 43543, 43510,
       39883, 45070,

In [ ]:
# Finance_Department

In [28]:
Finance_Department=HR_Department*25
Finance_Department

array([1081875, 1158750, 1035050, 1078600,  890800,  668175, 1167850,
        808875,  970950,  682825,  658900,  821550,  898625, 1220725,
        736175, 1076550,  695875, 1040575, 1130875,  794050,  653950,
        720925, 1079125, 1204225,  822225, 1171875, 1071900, 1099175,
        928475, 1093600,  892950,  773075,  987525,  897975,  859150,
        869875,  707975, 1151500, 1134050, 1139250,  715150,  681750,
        733525, 1206300,  660975, 1030300,  829350, 1049300, 1232225,
        703850, 1094150,  698500, 1178150,  741175,  738950,  741775,
       1117350, 1019775, 1032400,  969850,  755200, 1045025,  943175,
        924575,  772050, 1063400,  749250, 1200825,  740200,  758350,
       1226650, 1245500, 1197300,  625300,  905825,  895550,  632625,
       1194175,  813250,  742975, 1219750,  895925, 1020950,  752500,
        880050,  911200,  868325, 1152000,  859500,  630225,  888300,
        743725,  790775, 1082225, 1100450, 1114900,  926650, 1054900,
       1035625,  788

In [ ]:
# Sales_Department

In [34]:
Sales_Department=Finance_Department/2
Sales_Department


array([540937.5, 579375. , 517525. , 539300. , 445400. , 334087.5,
       583925. , 404437.5, 485475. , 341412.5, 329450. , 410775. ,
       449312.5, 610362.5, 368087.5, 538275. , 347937.5, 520287.5,
       565437.5, 397025. , 326975. , 360462.5, 539562.5, 602112.5,
       411112.5, 585937.5, 535950. , 549587.5, 464237.5, 546800. ,
       446475. , 386537.5, 493762.5, 448987.5, 429575. , 434937.5,
       353987.5, 575750. , 567025. , 569625. , 357575. , 340875. ,
       366762.5, 603150. , 330487.5, 515150. , 414675. , 524650. ,
       616112.5, 351925. , 547075. , 349250. , 589075. , 370587.5,
       369475. , 370887.5, 558675. , 509887.5, 516200. , 484925. ,
       377600. , 522512.5, 471587.5, 462287.5, 386025. , 531700. ,
       374625. , 600412.5, 370100. , 379175. , 613325. , 622750. ,
       598650. , 312650. , 452912.5, 447775. , 316312.5, 597087.5,
       406625. , 371487.5, 609875. , 447962.5, 510475. , 376250. ,
       440025. , 455600. , 434162.5, 576000. , 429750. , 31511

In [ ]:
# IT_Department

In [36]:
IT_Department=HR_Department+5000
IT_Department

array([48275, 51350, 46402, 48144, 40632, 31727, 51714, 37355, 43838,
       32313, 31356, 37862, 40945, 53829, 34447, 48062, 32835, 46623,
       50235, 36762, 31158, 33837, 48165, 53169, 37889, 51875, 47876,
       48967, 42139, 48744, 40718, 35923, 44501, 40919, 39366, 39795,
       33319, 51060, 50362, 50570, 33606, 32270, 34341, 53252, 31439,
       46212, 38174, 46972, 54289, 33154, 48766, 32940, 52126, 34647,
       34558, 34671, 49694, 45791, 46296, 43794, 35208, 46801, 42727,
       41983, 35882, 47536, 34970, 53033, 34608, 35334, 54066, 54820,
       52892, 30012, 41233, 40822, 30305, 52767, 37530, 34719, 53790,
       40837, 45838, 35100, 40202, 41448, 39733, 51080, 39380, 30209,
       40532, 34749, 36631, 48289, 49018, 49596, 42066, 47196, 46425,
       36525, 44269, 52646, 44436, 46321, 54261, 49231, 49824, 32848,
       37536, 33322, 50772, 40277, 32889, 40976, 40384, 50004, 40941,
       34105, 49456, 47906, 30784, 44819, 31695, 46233, 48543, 48510,
       44883, 50070,

In [ ]:
# task 3 (The department_wise of otal expensive of company)

In [39]:
HR_Department=np.arange(1,501,1,int)
Finance_Deprtment=np.arange(501,1001,1,int)
IT_Department=np.arange(1002,1501,1,int)
Sales_Department=np.arange(1502,2001,1,int)

In [53]:
#HR
HR_Total=np.sum(HR_Department)
HR_Total


125250

In [56]:
#Finance
Finance_Total=np.sum(Finance_Department)
Finance_Total

471570350

In [57]:
#Sales
Sales_Total=np.sum(Sales_Department)
Sales_Total

873749

In [58]:
#IT
IT_Total=np.sum(IT_Department)
IT_Total

624249

In [ ]:
# task 4

In [63]:
HR_Department.sort()
HR_Department
HR_Department[-10:]

array([491, 492, 493, 494, 495, 496, 497, 498, 499, 500])

In [64]:
Finance_Department.sort()
Finance_Department
Finance_Department[-10:]

array([1238700, 1241150, 1241975, 1242275, 1242950, 1243750, 1244275,
       1245500, 1246250, 1248475])

In [ ]:
# task 5

In [80]:
IT_Department_45000=np.sum(IT_Department>45000)
print(IT_Department_45000)

TypeError: '>' not supported between instances of 'tuple' and 'int'

In [83]:
Sales_Department_45000=np.sum(Sales_Department>45000)
print(Sales_Department_45000)

0


In [ ]:
# task 6

In [86]:
New_Sales_Department=.10*(Sales_Department>45000)+Sales_Department
print(New_Sales_Department)

[1502. 1503. 1504. 1505. 1506. 1507. 1508. 1509. 1510. 1511. 1512. 1513.
 1514. 1515. 1516. 1517. 1518. 1519. 1520. 1521. 1522. 1523. 1524. 1525.
 1526. 1527. 1528. 1529. 1530. 1531. 1532. 1533. 1534. 1535. 1536. 1537.
 1538. 1539. 1540. 1541. 1542. 1543. 1544. 1545. 1546. 1547. 1548. 1549.
 1550. 1551. 1552. 1553. 1554. 1555. 1556. 1557. 1558. 1559. 1560. 1561.
 1562. 1563. 1564. 1565. 1566. 1567. 1568. 1569. 1570. 1571. 1572. 1573.
 1574. 1575. 1576. 1577. 1578. 1579. 1580. 1581. 1582. 1583. 1584. 1585.
 1586. 1587. 1588. 1589. 1590. 1591. 1592. 1593. 1594. 1595. 1596. 1597.
 1598. 1599. 1600. 1601. 1602. 1603. 1604. 1605. 1606. 1607. 1608. 1609.
 1610. 1611. 1612. 1613. 1614. 1615. 1616. 1617. 1618. 1619. 1620. 1621.
 1622. 1623. 1624. 1625. 1626. 1627. 1628. 1629. 1630. 1631. 1632. 1633.
 1634. 1635. 1636. 1637. 1638. 1639. 1640. 1641. 1642. 1643. 1644. 1645.
 1646. 1647. 1648. 1649. 1650. 1651. 1652. 1653. 1654. 1655. 1656. 1657.
 1658. 1659. 1660. 1661. 1662. 1663. 1664. 1665. 16

In [89]:
x_10=Sales_Department[New_Sales_Department<45000]
x_10*.10+x_10

array([1652.2, 1653.3, 1654.4, 1655.5, 1656.6, 1657.7, 1658.8, 1659.9,
       1661. , 1662.1, 1663.2, 1664.3, 1665.4, 1666.5, 1667.6, 1668.7,
       1669.8, 1670.9, 1672. , 1673.1, 1674.2, 1675.3, 1676.4, 1677.5,
       1678.6, 1679.7, 1680.8, 1681.9, 1683. , 1684.1, 1685.2, 1686.3,
       1687.4, 1688.5, 1689.6, 1690.7, 1691.8, 1692.9, 1694. , 1695.1,
       1696.2, 1697.3, 1698.4, 1699.5, 1700.6, 1701.7, 1702.8, 1703.9,
       1705. , 1706.1, 1707.2, 1708.3, 1709.4, 1710.5, 1711.6, 1712.7,
       1713.8, 1714.9, 1716. , 1717.1, 1718.2, 1719.3, 1720.4, 1721.5,
       1722.6, 1723.7, 1724.8, 1725.9, 1727. , 1728.1, 1729.2, 1730.3,
       1731.4, 1732.5, 1733.6, 1734.7, 1735.8, 1736.9, 1738. , 1739.1,
       1740.2, 1741.3, 1742.4, 1743.5, 1744.6, 1745.7, 1746.8, 1747.9,
       1749. , 1750.1, 1751.2, 1752.3, 1753.4, 1754.5, 1755.6, 1756.7,
       1757.8, 1758.9, 1760. , 1761.1, 1762.2, 1763.3, 1764.4, 1765.5,
       1766.6, 1767.7, 1768.8, 1769.9, 1771. , 1772.1, 1773.2, 1774.3,
      

In [98]:
x_10=New_Sales_Department<45000
New_Sales_Department[x_10]=New_Sales_Department[x_10]*.10+New_Sales_Department[x_10]


In [99]:
New_Sales_Department

array([2199.0782, 2200.5423, 2202.0064, 2203.4705, 2204.9346, 2206.3987,
       2207.8628, 2209.3269, 2210.791 , 2212.2551, 2213.7192, 2215.1833,
       2216.6474, 2218.1115, 2219.5756, 2221.0397, 2222.5038, 2223.9679,
       2225.432 , 2226.8961, 2228.3602, 2229.8243, 2231.2884, 2232.7525,
       2234.2166, 2235.6807, 2237.1448, 2238.6089, 2240.073 , 2241.5371,
       2243.0012, 2244.4653, 2245.9294, 2247.3935, 2248.8576, 2250.3217,
       2251.7858, 2253.2499, 2254.714 , 2256.1781, 2257.6422, 2259.1063,
       2260.5704, 2262.0345, 2263.4986, 2264.9627, 2266.4268, 2267.8909,
       2269.355 , 2270.8191, 2272.2832, 2273.7473, 2275.2114, 2276.6755,
       2278.1396, 2279.6037, 2281.0678, 2282.5319, 2283.996 , 2285.4601,
       2286.9242, 2288.3883, 2289.8524, 2291.3165, 2292.7806, 2294.2447,
       2295.7088, 2297.1729, 2298.637 , 2300.1011, 2301.5652, 2303.0293,
       2304.4934, 2305.9575, 2307.4216, 2308.8857, 2310.3498, 2311.8139,
       2313.278 , 2314.7421, 2316.2062, 2317.6703, 

In [ ]:
# task 7
# task 1

In [104]:
import pandas as pd

In [106]:
df=pd.read_csv("DS1_C4_S1_AdmissionPredict_Data_Practice.csv")
df             


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [112]:
df[df['GRE Score']>320].shape

(163, 9)

In [ ]:
# task 2

In [114]:
df[df['TOEFL Score']>110]

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
5             6        330          115                  5  4.5   3.0  9.34   
11           12        327          111                  4  4.0   4.5  9.00   
12           13        328          112                  4  4.0   4.5  9.10   
21           22        325          114                  4  3.0   2.0  8.40   
..          ...        ...          ...                ...  ...   ...   ...   
385         386        335          117                  5  5.0   5.0  9.82   
392         393        326          112                  4  4.0   3.5  9.12   
394         395        329          111                  4  4.5   4.0  9.23   
397         398        330          116                  4  5.0   4.5  9.45   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
5           1              0.90  
11          1              0.84  
12          1              0.78  
21          0              0.70  
..        ...               ...  
385         1              0.96  
392         1              0.84  
394         1              0.89  
397         1              0.91  
399         1              0.95  

[120 rows x 9 columns]

In [ ]:
# task 3

In [118]:
df[(df['TOEFL Score']>110) & (df['GRE Score']>320)]['Serial No.']

0        1
5        6
11      12
12      13
21      22
      ... 
385    386
392    393
394    395
397    398
399    400
Name: Serial No., Length: 114, dtype: int64